baseURL = "https://dot-ry.fi/"
languageCode = "en-us"
title = "DOT ry"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "News"
    pageRef = "news"
    weight = 2
  [[menu.main]]
    name = "Join"
    url = "https://docs.google.com/forms/d/e/1FAIpQLSe_albzmj_VINAI47fbUw44LygX9pTxfOS4s22aDQQkIxuYAw/viewform"
    weight = 3
  [[menu.main]]
    name = "Graffathon"
    url = "https://graffathon.org"
    weight = 4
  [[menu.main]]
    name = "Contact"
    pageRef = "contact"
    weight = 5

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
