baseURL = "https://dot-ry.fi/"
languageCode = "en-us"
title = "DOT ry"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "News"
    pre = "edit"
    url = "/news/"
    weight = 2
  [[menu.main]]
    name = "Join"
    pre = "edit"
    url = "/join/"
    weight = 3
  [[menu.main]]
    name = "Graffathon"
    pre = "edit"
    url = "https://graffathon.org"
    weight = 4
  [[menu.main]]
    name = "Contact"
    pre = "edit"
    url = "/contact"
    weight = 5

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
